### ISSUE TITLE
[Samplescenes tests] TestGetApplicationScreensize() fails on iOS for C#, Python and Java

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1096]
## Steps to reproduce
 
- For Samplescenes run TestGetApplicationScreensize() for C#, Python and Java and check the test result

### AR
 
The test fails on each language and the error log says:
```
com.alttester.altTesterExceptions.MethodNotFoundException: Method SetResolution not found in UnityEngine.Screen
 at com.alttester.MessageHandler.handleErrors(MessageHandler.java:176)
 at com.alttester.MessageHandler.receive(MessageHandler.java:100)
 at com.alttester.Commands.AltBaseCommand.recvall(AltBaseCommand.java:21)
 at com.alttester.Commands.AltCallStaticMethod.Execute(AltCallStaticMethod.java:17)
 at com.alttester.AltDriver.callStaticMethod(AltDriver.java:326)
 at com.alttester.TestsSampleScene1.TestGetApplicationScreenSize(TestsSampleScene1.java:235)
```

### Additional info
 
Testing environment
- device for tests performed: iPhone 6 iOS 12.5.6
- intrumented build created on MacOS in Unity v `2021.3.16f1`
- _AltTester Unity SDK_ from `development` branch (01.02.2023)

Screenshots 
![image](https://user-images.githubusercontent.com/62327834/216080422-6caeaf64-a659-41dd-9807-b3a6d307b95c.png)
![image](https://user-images.githubusercontent.com/62327834/216080513-0076da8d-aa65-4bf5-b4cc-5e31b36019ea.png)

### ER
 
The test should pass with no errors in all languages

**Comment by iulianatodoran** [comment]
@sandraaltom I put this in `Investigate`, it is an issue found during testing for 1.8.2 Hotfix.

**Comment by iulianatodoran** [comment]
### Testing environment
- devices for tests performed: iPhone 6 (iOS 12.5.6), Xiaomi Mi Note 10 Lite (Android 12)
- intrumented build created on MacOS in Unity v 2021.3.16f1
- AltTester Unity SDK from `development` branch (10.07.2023)

### Tests performed and results
- ✅ Checked on all languages that the test passes on an iOS device
- ✅ Checked on all languages that the test passes on an Android device also

### Conclusion
The implemented fix solved the issue by adapting the test to be compliant for the iOS device (since the resolution on the iOS cannot be set and the main goal of the test is to see that it returns a value that is different than 0)

**Closing the ticket.**
